name = "holo-backend"
compatibility_date = "2024-02-26"

[vars]
NODE_ENV = "production"

# Declare environment variables that will be bound to secrets
[vars.env]
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
BETTER_AUTH_SECRET = ""
GEMINI_API_KEY = ""
RESEND_API_KEY = ""
RESEND_FROM = ""
DATABASE_URL = ""

# The following secrets need to be set using wrangler secret:
# - DATABASE_URL
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - BETTER_AUTH_SECRET
# - GEMINI_API_KEY
# - RESEND_API_KEY
# - RESEND_FROM

# Database URL will be set using wrangler secret
# Run: wrangler secret put DATABASE_URL

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxx"
# preview_id = "xxx"
